# Author Settings
author: Quan Nguyen Van # add your name
author-img: # add your photo
about-author: I am a AI engineer focusing on Computer Vision on industrial side. Always hungry to keep learning. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: quanap5kr # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: # add your Email address

plugins:  
    - jekyll-paginate
    - jekyll-redirect-from

markdown: kramdown
kramdown:
    highlighter: rouge
    syntax_highlighter_opts:
        block:
            line_numbers: true

# More › http://kramdown.gettalong.org/quickre...
# Options › http://kramdown.gettalong.org/options...
kramdown:
  input: GFM
  # https://github.com/jekyll/jekyll/pull...
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_...
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-o...
    css_class: 'background'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
#       start_line: 1

